[package]
name = "script_repl"
version = "0.1.0"
authors = ["imkiva <libkernelpanic@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "6.0.0"
